######################################################################################
server:
  port: 9009
#######################################################################################
#################################Spring配置#############################################
spring:
  profiles:
    active: dev
  tomcat:
    max-http-post-size: -1
  thymeleaf:
    mode: HTML
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/
#######################################################################################

########################MapperXml######################################################
mybatis:
  mapper-locations: classpath:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.ucaner.skeleton.service.**.entity  # 注意：对应实体类的路径
#######################################################################################


##########################pagehelper配置###############################################
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#######################################################################################

######################################es###############################################
#elasticsearch:
#  cluster-nodes: 127.0.0.1:9200

###################################swagger############################################
swagger:
  enabled: true
###################################swagger############################################

###################################xxljob############################################
xxljob:
  enabled: false
###################################xxljob############################################

###################################ehcache############################################
ehcache:
  enabled: true
###################################ehcache############################################
