#!/bin/sh
### BEGIN INIT INFO
# Provides:          skeleton-xxljob
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6
# Short-Description: skeleton-xxljob Server
# Description:       skeleton-xxljob Server
### END INIT INFO

do_start()
{
        echo "start skeleton-xxljob ..."
        sh /skeleton/xxl-job/app/startxxlJob.sh

        return 0
}

do_stop()
{
        echo "stop skeleton-xxljob ..."
        sh /skeleton/xxl-job/app/stopxxlJob.sh

        return 0
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
esac

exit 0
:
