######################################################################################
server:
  port: 9009
#######################################################################################

#################################Spring配置#############################################
spring:
  profiles:
    active: dev
  tomcat:
    max-http-post-size: -1
#######################################################################################

##########################pagehelper配置###############################################
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#######################################################################################

