######################################################################################
server:
  port: 9009
#######################################################################################
#################################Spring配置#############################################
spring:
  profiles:
    active: dev
  tomcat:
    max-http-post-size: -1
#######################################################################################
