#################################Spring配置#############################################
spring:
  profiles:
    active: dev

server:
  port: 9090
  tomcat:
    max-http-post-size: -1
#######################################################################################

########################MapperXml######################################################
mybatis:
  mapper-locations: classpath:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.ucaner.skeleton.service.**.entity  # 注意：对应实体类的路径
#######################################################################################


##########################pagehelper配置###############################################
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#######################################################################################