##########################Spring配置############################
spring:
  profiles:
    active: dev
###############################################################

###############################################################
##指向mapper的xml文件位置
#mybatis.mapper-locations=mapper.**.*Mapper.xml
  #mybatis.type-aliases-package=cn.ucaner.wx.app.service.*.dao
mybatis:
  mapper-locations: mapper.**.*Mapper.xml
  type-aliases-package:
################################################################


###############pagehelper配置#######################
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

####################################################