######################################################################################
server:
  port: 9002
#######################################################################################
#################################Spring配置#############################################
spring:
  profiles:
    active: dev
  tomcat:
    max-http-post-size: -1
  kafka:
    #kafka地址
    bootstrap-servers: localhost:9092
    consumer:
      #指定默认消费者group id
      groupId: executor
      #指定消息被消费之后自动提交偏移量,以便下次继续消费
      enable-auto-commit: true
      ## 指定消息key和消息体的编解码方式
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      groupId: executor
      #指定从最近地方开始消费(earliest)
      #指定消息key和消息体的编解码方式
      keyDeserializer: org.apache.kafka.common.serialization.StringSerializer
      valueDserializer: org.apache.kafka.common.serialization.StringSerializer
      ##每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432

#######################################################################################

########################MapperXml######################################################
mybatis:
  mapper-locations: classpath:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.ucaner.skeleton.service.**.entity  # 注意：对应实体类的路径
#######################################################################################


##########################pagehelper配置###############################################
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#######################################################################################

######################################es###############################################
#elasticsearch:
#  cluster-nodes: 127.0.0.1:9200

###################################swagger############################################
swagger:
  enabled: true
###################################swagger############################################

###################################xxljob############################################
xxljob:
  enabled: false
###################################xxljob############################################

###################################ehcache############################################
ehcache:
  enabled: true
###################################ehcache############################################
