#!/bin/sh
# postrm script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

########清除安装目录里面的数据
if [ -d "/skeleton/xxl-job/app" ]; then
	rm -rf "/skeleton/xxl-job/app"
fi


if [ "$1" = "purge" ] ; then
        update-rc.d skeleton-xxljob remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
        systemctl --system daemon-reload >/dev/null || true
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge
fi
# End automatically added section


exit 0
