#! /bin/sh
# prerm script for #PACKAGE#
#
# see: dh_installdeb(1)

############## 如果文件存在且可以执行 ##################
if [ -x "/etc/init.d/skeleton-xxljob" ]; then
        invoke-rc.d skeleton-xxljob stop || true
fi

exit 0
